# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20180807_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danceclass',
            old_name='class_time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='danceclass',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
