# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-04 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_danceclass_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='secondary_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Unregistered', 'Unregistered'), ('Pre-Registered', 'Pre-Registered'), ('Registered', 'Registered'), ('Unpaid', 'Unpaid')], default='Unregistered', max_length=20),
        ),
    ]
