# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-08 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_auto_20181108_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
