# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-05 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_auto_20181204_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='medical',
            field=models.TextField(null=True),
        ),
    ]
