# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-05 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_auto_20181108_0455'),
        ('classes', '0010_student_medical'),
    ]

    operations = [
    ]
