# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-10 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_auto_20181206_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
