# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-20 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_parent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='age_range',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
