# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-03 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_danceclass_age_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10, null=True),
        ),
    ]
