# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-31 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
