# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-26 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0019_auto_20190626_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
