# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-31 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0021_parent_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=20)),
                ('spots', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='FreeStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=70)),
                ('parent_email', models.EmailField(max_length=254)),
                ('num_children', models.IntegerField()),
                ('free_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.FreeClass')),
            ],
        ),
    ]
